use zctf_schema::{RecordKind, Schema, SchemaFragment, Type};

pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

#[derive(Debug, Clone)]
pub struct GeneratedFile {
    pub name: String,
    pub contents: String,
}

#[derive(Debug, Clone)]
pub struct Options {
    pub runtime_import: String,
}
impl Default for Options {
    fn default() -> Self {
        Self {
            runtime_import: "@zctf/runtime".into(),
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct Layout {
    size: usize,
    align: usize,
}

fn align_up(value: usize, align: usize) -> usize {
    (value + align - 1) & !(align - 1)
}

fn type_layout(ty: &Type, schema: &Schema, stack: &mut Vec<String>) -> Result<Layout> {
    Ok(match ty {
        Type::Bool | Type::U8 | Type::I8 => Layout { size: 1, align: 1 },
        Type::U16 | Type::I16 => Layout { size: 2, align: 2 },
        Type::U32 | Type::I32 | Type::F32 | Type::String { .. } | Type::List { .. } => {
            Layout { size: 4, align: 4 }
        }
        Type::U64 | Type::I64 | Type::F64 => Layout { size: 8, align: 8 },
        Type::Option { item } => {
            let inner = type_layout(item, schema, stack)?;
            Layout {
                size: align_up(1, inner.align) + inner.size,
                align: inner.align,
            }
        }
        Type::Named { name } => {
            if let Some(value) = schema.enums.get(name) {
                repr_layout(value.repr.as_deref().unwrap_or("u8"))?
            } else {
                if stack.contains(name) {
                    return Err(format!("recursive record {name} is unsupported").into());
                }
                let record = schema
                    .records
                    .get(name)
                    .ok_or_else(|| format!("unknown named type {name}"))?;
                stack.push(name.clone());
                let layout = record_layout(record, schema, stack)?;
                stack.pop();
                layout
            }
        }
    })
}

fn repr_layout(repr: &str) -> Result<Layout> {
    Ok(match repr {
        "u8" | "i8" => Layout { size: 1, align: 1 },
        "u16" | "i16" => Layout { size: 2, align: 2 },
        "u32" | "i32" => Layout { size: 4, align: 4 },
        "u64" | "i64" => Layout { size: 8, align: 8 },
        _ => return Err(format!("unsupported enum repr {repr}").into()),
    })
}

fn record_layout(
    record: &SchemaFragment,
    schema: &Schema,
    stack: &mut Vec<String>,
) -> Result<Layout> {
    let mut cursor = 0;
    let mut alignment = 1;
    for field in record.fields.iter().filter(|f| !f.skip) {
        let layout = type_layout(&field.ty, schema, stack)?;
        cursor = align_up(cursor, layout.align) + layout.size;
        alignment = alignment.max(layout.align);
    }
    Ok(Layout {
        size: align_up(cursor, alignment),
        align: alignment,
    })
}

fn field_offsets(record: &SchemaFragment, schema: &Schema) -> Result<Vec<(usize, Layout)>> {
    let mut cursor = 0;
    let mut output = Vec::new();
    for field in record.fields.iter().filter(|f| !f.skip) {
        let layout = type_layout(&field.ty, schema, &mut vec![record.name.clone()])?;
        cursor = align_up(cursor, layout.align);
        output.push((cursor, layout));
        cursor += layout.size;
    }
    Ok(output)
}

pub fn generate(schema: &Schema, emits: &[&str], options: &Options) -> Result<Vec<GeneratedFile>> {
    let stem = kebab(&schema.name);
    let mut files = Vec::new();
    for emit in emits {
        match *emit {
            "js" => files.push(GeneratedFile {
                name: format!("{stem}.view.js"),
                contents: generate_js(schema, options)?,
            }),
            "ts" => files.push(GeneratedFile {
                name: format!("{stem}.d.ts"),
                contents: generate_ts(schema)?,
            }),
            "rust" => files.push(GeneratedFile {
                name: format!("{}.generated.rs", snake(&schema.name)),
                contents: generate_rust(schema)?,
            }),
            other => return Err(format!("unsupported emit target {other}").into()),
        }
    }
    Ok(files)
}

fn header(schema: &Schema, prefix: &str) -> String {
    format!(
        "{prefix} Generated by zctf-codegen.\n{prefix} Schema: {}\n{prefix} Schema ID: {}\n{prefix} Layout version: {}\n{prefix} Do not edit manually.\n",
        schema.name, schema.schema_id, schema.layout_version
    )
}

fn generate_js(schema: &Schema, options: &Options) -> Result<String> {
    let mut out = header(schema, "//");
    out.push_str(&format!(
        "import {{ ZctfDocument, ZctfFixedListView }} from {:?};\n\n",
        options.runtime_import
    ));
    out.push_str(&format!(
        "const SCHEMA_ID = {}n;\nconst LAYOUT_VERSION = {};\n\n",
        schema.schema_id, schema.layout_version
    ));
    for value in schema.enums.values() {
        out.push_str(&format!("export const {} = Object.freeze({{\n", value.name));
        for variant in &value.variants {
            out.push_str(&format!("  {}: {},\n", variant.name, variant.value));
        }
        out.push_str("});\n\n");
    }
    for record in schema
        .records
        .values()
        .filter(|r| r.kind == RecordKind::Record)
    {
        emit_js_record(&mut out, record, schema, false)?;
        emit_js_list(&mut out, record, schema)?;
    }
    let root = schema
        .records
        .get(&schema.root)
        .ok_or("root record missing")?;
    emit_js_record(&mut out, root, schema, true)?;
    Ok(out)
}

fn emit_js_record(
    out: &mut String,
    record: &SchemaFragment,
    schema: &Schema,
    root: bool,
) -> Result<()> {
    out.push_str(&format!("export class {}View {{\n  constructor(document, offset) {{ this.document = document; this.offset = offset; }}\n", record.name));
    if root {
        out.push_str(&format!("  static from(bytes) {{\n    const document = ZctfDocument.from(bytes, {{ schemaId: SCHEMA_ID, layoutVersion: LAYOUT_VERSION }});\n    return new {}View(document, document.rootOffset);\n  }}\n", record.name));
    }
    let offsets = field_offsets(record, schema)?;
    for (field, (offset, _)) in record.fields.iter().filter(|f| !f.skip).zip(offsets) {
        out.push_str(&format!(
            "  get {}() {{ {} }}\n",
            field.js_name,
            js_read(&field.ty, offset, schema)?
        ));
    }
    out.push_str("  toObject() {\n    return {\n");
    for field in record.fields.iter().filter(|f| !f.skip) {
        let suffix = match &field.ty {
            Type::List { .. } => ".toArray()",
            Type::Named { name } if schema.records.contains_key(name) => ".toObject()",
            Type::Option { item } if matches!(&**item, Type::Named { name } if schema.records.contains_key(name)) => {
                "?.toObject()"
            }
            _ => "",
        };
        out.push_str(&format!(
            "      {}: this.{}{},\n",
            field.js_name, field.js_name, suffix
        ));
    }
    out.push_str("    };\n  }\n}\n\n");
    Ok(())
}

fn js_read(ty: &Type, offset: usize, schema: &Schema) -> Result<String> {
    let absolute = format!("this.offset + {offset}");
    Ok(match ty {
        Type::Bool => format!("return this.document.u8({absolute}) !== 0;"),
        Type::U8 => format!("return this.document.u8({absolute});"),
        Type::I8 => format!("return this.document.i8({absolute});"),
        Type::U16 => format!("return this.document.u16({absolute});"),
        Type::I16 => format!("return this.document.i16({absolute});"),
        Type::U32 => format!("return this.document.u32({absolute});"),
        Type::I32 => format!("return this.document.i32({absolute});"),
        Type::U64 => format!("return this.document.u64({absolute});"),
        Type::I64 => format!("return this.document.i64({absolute});"),
        Type::F32 => format!("return this.document.f32({absolute});"),
        Type::F64 => format!("return this.document.f64({absolute});"),
        Type::String { .. } => {
            format!("return this.document.string(this.document.u32({absolute}));")
        }
        Type::List { item } => {
            let Type::Named { name } = &**item else {
                return Err("only Vec<Record> is supported".into());
            };
            let record = schema
                .records
                .get(name)
                .ok_or_else(|| format!("unknown list record {name}"))?;
            let layout = record_layout(record, schema, &mut vec![name.clone()])?;
            format!(
                "return new {}ListView(this.document, this.document.u32({absolute}), {});",
                name, layout.size
            )
        }
        Type::Named { name } if schema.enums.contains_key(name) => {
            let repr = schema.enums[name].repr.as_deref().unwrap_or("u8");
            let method = if let Some(width) = repr.strip_prefix('i') {
                format!("i{width}")
            } else {
                repr.into()
            };
            format!("return this.document.{method}({absolute});")
        }
        Type::Named { name } => format!("return new {name}View(this.document, {absolute});"),
        Type::Option { item } => {
            let layout = type_layout(item, schema, &mut vec![])?;
            let inner_offset = align_up(1, layout.align);
            let mut inner = js_read(item, offset + inner_offset, schema)?;
            inner = inner
                .trim_start_matches("return ")
                .trim_end_matches(';')
                .to_string();
            format!("return this.document.u8({absolute}) === 0 ? undefined : ({inner});")
        }
    })
}

fn emit_js_list(out: &mut String, record: &SchemaFragment, schema: &Schema) -> Result<()> {
    let layout = record_layout(record, schema, &mut vec![record.name.clone()])?;
    out.push_str(&format!(
        "export class {}ListView extends ZctfFixedListView {{\n  constructor(document, offset, stride = {}) {{\n    super(document, offset, stride, (doc, itemOffset) => new {}View(doc, itemOffset));\n  }}\n}}\n\n",
        record.name, layout.size, record.name));
    Ok(())
}

fn generate_ts(schema: &Schema) -> Result<String> {
    let mut out = header(schema, "//");
    for value in schema.enums.values() {
        out.push_str(&format!("export declare const {}: {{\n", value.name));
        for variant in &value.variants {
            out.push_str(&format!(
                "  readonly {}: {};\n",
                variant.name, variant.value
            ));
        }
        out.push_str("};\n");
        out.push_str(&format!(
            "export type {} = {};\n\n",
            value.name,
            value
                .variants
                .iter()
                .map(|v| v.value.to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        ));
    }
    for record in schema.records.values() {
        out.push_str(&format!("export interface {}Object {{\n", record.name));
        for field in record.fields.iter().filter(|f| !f.skip) {
            out.push_str(&format!(
                "  {}: {};\n",
                field.js_name,
                ts_type(&field.ty, schema, true)?
            ));
        }
        out.push_str("}\n\n");
    }
    for record in schema
        .records
        .values()
        .filter(|r| r.kind == RecordKind::Record)
    {
        out.push_str(&format!("export declare class {}ListView implements Iterable<{}View> {{\n  readonly length: number;\n  get(index: number): {}View;\n  at(index: number): {}View | undefined;\n  toArray(): {}Object[];\n  [Symbol.iterator](): IterableIterator<{}View>;\n}}\n\n",
            record.name, record.name, record.name, record.name, record.name, record.name));
    }
    for record in schema.records.values() {
        out.push_str(&format!("export declare class {}View {{\n", record.name));
        if record.kind == RecordKind::Document {
            out.push_str(&format!(
                "  static from(bytes: Uint8Array | ArrayBuffer): {}View;\n",
                record.name
            ));
        }
        for field in record.fields.iter().filter(|f| !f.skip) {
            out.push_str(&format!(
                "  readonly {}: {};\n",
                field.js_name,
                ts_type(&field.ty, schema, false)?
            ));
        }
        out.push_str(&format!("  toObject(): {}Object;\n}}\n\n", record.name));
    }
    Ok(out)
}

fn ts_type(ty: &Type, schema: &Schema, object: bool) -> Result<String> {
    Ok(match ty {
        Type::Bool => "boolean".into(),
        Type::U64 | Type::I64 => "bigint".into(),
        Type::U8
        | Type::U16
        | Type::U32
        | Type::I8
        | Type::I16
        | Type::I32
        | Type::F32
        | Type::F64 => "number".into(),
        Type::String { .. } => "string".into(),
        Type::Option { item } => format!("{} | undefined", ts_type(item, schema, object)?),
        Type::List { item } => {
            let Type::Named { name } = &**item else {
                return Err("only record lists are supported".into());
            };
            if object {
                format!("{name}Object[]")
            } else {
                format!("{name}ListView")
            }
        }
        Type::Named { name } if schema.enums.contains_key(name) => name.clone(),
        Type::Named { name } => {
            if object {
                format!("{name}Object")
            } else {
                format!("{name}View")
            }
        }
    })
}

fn generate_rust(schema: &Schema) -> Result<String> {
    let mut out = header(schema, "//");
    out.push_str(&format!(
        "pub const SCHEMA_ID: u64 = {};\npub const LAYOUT_VERSION: u32 = {};\n",
        schema.schema_id, schema.layout_version
    ));
    for record in schema.records.values() {
        let offsets = field_offsets(record, schema)?;
        out.push_str(&format!("\npub mod {} {{\n", snake(&record.name)));
        for (field, (offset, _)) in record.fields.iter().filter(|f| !f.skip).zip(offsets) {
            out.push_str(&format!(
                "    pub const {}: usize = {};\n",
                field.rust_name.to_uppercase(),
                offset
            ));
        }
        out.push_str("}\n");
    }
    Ok(out)
}

fn kebab(value: &str) -> String {
    words(value).join("-")
}
fn snake(value: &str) -> String {
    words(value).join("_")
}
fn words(value: &str) -> Vec<String> {
    let mut words = vec![String::new()];
    for ch in value.chars() {
        if ch.is_uppercase() && !words.last().unwrap().is_empty() {
            words.push(String::new());
        }
        words.last_mut().unwrap().extend(ch.to_lowercase());
    }
    words
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn names_are_converted() {
        assert_eq!(kebab("TransformResult"), "transform-result");
        assert_eq!(snake("TransformResult"), "transform_result");
    }
}
