import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const supported = /^(u32|u64|f64|bool|enum8|StringRef|FixedList<.+>)$/;
const schemaPaths = process.argv.slice(2);
if (schemaPaths.length === 0) {
  throw new TypeError("usage: node scripts/generate.js <schema.json> [...]");
}

const constantName = (value) => value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

for (const schemaPath of schemaPaths) {
  const schema = JSON.parse(await readFile(resolve(root, schemaPath), "utf8"));
  for (const [recordName, record] of Object.entries(schema.records)) {
    for (const [fieldName, field] of Object.entries(record.fields)) {
      if (!supported.test(field.type)) {
        throw new TypeError(`${recordName}.${fieldName}: unsupported type ${field.type}`);
      }
    }
  }

  for (const target of schema.outputs) {
    let output = "// Generated by scripts/generate.js. Do not edit.\n\n";
    for (const recordName of target.records) {
      const record = schema.records[recordName];
      if (!record) throw new TypeError(`unknown output record: ${recordName}`);
      const name = constantName(recordName);
      output += `export const ${name} = Object.freeze(${JSON.stringify(
        {
          ...(record.offset === undefined ? {} : { offset: record.offset }),
          size: record.size,
          fields: Object.fromEntries(
            Object.entries(record.fields).map(([field, definition]) => [field, definition.offset]),
          ),
        },
        null,
        2,
      )});\n\n`;
    }
    const enums = Object.fromEntries(target.enums.map((name) => {
      if (!schema.enums[name]) throw new TypeError(`unknown output enum: ${name}`);
      return [name, schema.enums[name]];
    }));
    output += `export const ENUMS = Object.freeze(${JSON.stringify(enums, null, 2)});\n`;
    await writeFile(resolve(root, target.path), output);
  }
}
