import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const schema = JSON.parse(await readFile(resolve(root, "schemas/zctf.schema.json"), "utf8"));
const supported = /^(u32|u64|f64|bool|enum8|StringRef|FixedList<.+>)$/;

for (const [recordName, record] of Object.entries(schema.records)) {
  for (const [fieldName, field] of Object.entries(record.fields)) {
    if (!supported.test(field.type)) {
      throw new TypeError(`${recordName}.${fieldName}: unsupported type ${field.type}`);
    }
  }
}

const constantName = (value) => value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
let output = "// Generated by scripts/generate.js. Do not edit.\n\n";
for (const [recordName, record] of Object.entries(schema.records)) {
  const name = constantName(recordName);
  output += `export const ${name} = Object.freeze(${JSON.stringify(
    {
      offset: record.offset,
      size: record.size,
      fields: Object.fromEntries(
        Object.entries(record.fields).map(([field, definition]) => [field, definition.offset]),
      ),
    },
    null,
    2,
  )});\n\n`;
}
output += `export const CONFIG_ENUMS = Object.freeze(${JSON.stringify(schema.enums, null, 2)});\n`;
const transform = schema.records.TransformConfig;
const transformFields = Object.entries(transform.fields);
output += `\n// Schema-specific scalar compiler. Collection regions are written by the\n`;
output += `// specialized TransformConfig compiler after this hot root write.\n`;
output += `export function writeTransformConfigRoot(view, ${transformFields
  .map(([field]) => field)
  .join(", ")}) {\n`;
for (const [field, definition] of transformFields) {
  const offset = transform.offset + definition.offset;
  if (definition.type === "u32" || definition.type.startsWith("FixedList<")) {
    output += `  view.setUint32(${offset}, ${field}, true);\n`;
  } else if (definition.type === "f64") {
    output += `  view.setFloat64(${offset}, ${field}, true);\n`;
  } else if (definition.type === "enum8" || definition.type === "bool") {
    output += `  view.setUint8(${offset}, ${field});\n`;
  } else {
    throw new TypeError(`TransformConfig.${field}: no generated writer for ${definition.type}`);
  }
}
output += `}\n`;
await writeFile(resolve(root, "packages/runtime/src/layout.generated.js"), output);
